### PR TITLE
Add Boost-1.0 to Fedora

### PR DESCRIPTION
**Pull request by nmonti**
Addresses issue #76

### CODE REVIEW

**Comment by suve** [comment]
Uh, nope. As the README says, `fedora.txt` is based on the [Fedora Wiki](https://fedoraproject.org/wiki/Licensing:Main#Good_Licenses), and that list only allows `Boost`. So the package using `Boost-1.0` is actually a violation of Fedora's packaging guidelines.

There is some ongoing talk about [switching to SPDX identifiers in Fedora](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/2BU5JTWLCQWRSPMORNPJLOPLDYHINGMV/#WUAC2GDMWOBMFB57WXMZVRGNDEWDJKFN), so hopefully the various lists will start slowly converging over time.

**Comment by nmonti** [comment]
Interesting. The same exact license for Boost listed in that wiki is in Boost-1.0. It'd be goofy if they care more about the format than the text of the license, so I'll ~~propose the wiki edit~~ email them and see what they say

**Comment by nmonti** [comment]
Also for the record, BSL-1.0 is the SPDX identifier, not Boost-1.0: https://spdx.org/licenses/

**Comment by qrpnxz** [comment]
The appropriate list is [`tweaked`](https://github.com/suve/vrms-rpm/blob/96ce9d532fa7dbdb4a64b2caed7b723a66b57fee/licences/tweaked.txt). Change your patch and it will probably be merged.

**Comment by suve** [comment]
Closing this because:
1. The `Boost-1.0` identifier is not recognized as valid by [Fedora's licensing page](https://docs.fedoraproject.org/en-US/legal/allowed-licenses/), so it cannot go into the `fedora` list. The old Callaway-style identifier was simply `Boost`, and Fedora is currently undergoing a (very slow) transition towards SPDX identitifers; the SPDX identifier is `BSL-1.0`.
2. The `Boost-1.0` identifier is already part of the `tweaked` list, having been added in 0411fa8f4b13c21b105c89454d14daaaae45933e.

**Pull request closed without merging**
